package com.Proyecto.coffeepalace.ui.navigations

sealed class Screens(val route: String) {
    object HomeSeller : Screens("home_seller")
    object AddProduct : Screens("add_product")
    object Category : Screens("category")
    object Ingrediente : Screens("ingrediente")
    object AddReceta : Screens("add_receta")
    object DeleteProduct : Screens("delete_product")
    object ViewUsers : Screens("view_users")
    object DeleteReceta : Screens("delete_receta")
    object Orders : Screens("orders_screen")
    object Splash : Screens("splash_screen")
    object Login : Screens("login")
    object SignUp : Screens("signup")
    object ForgotPassword : Screens("forgot_password")
    object ProductDetail : Screens("product_detail")
    object Search : Screens("search")
    object RecipeDetail : Screens("recipe_detail/{recipeId}")

    object ViewStock : Screens("view_stock")
    object Comments : Screens("comments")
    object HomeClient : Screens("home_client")
    object ProfileClient : Screens("profile_client")
    object CarDetailsClient : Screens("car_details_client")
    object CheckoutClient : Screens("checkout_client")
    object ConfirmationPaymentClient : Screens("confirmation_payment_client")
    object HomeFilteredClient : Screens("home_filtered_client")
    object OrderDetailsClient : Screens("order_details_client")
    object GetStartedClient : Screens("get_started_client")
    object EntryPoints : Screens("entry_points")
}
